### ISSUE TITLE
Feedback meta-issue

### ISSUE THREAD

**Issue by graysonwright** [graysonwright/resume#1]
* [ ] @grayson your main content area is super wide, and looks kind of weird on a laptop. i’d narrow it by at least 2-300px.
* [ ] i like what you’re doing bolding keywords, but when you bold that many, it loses the impact. think about other ways you can pull out information: tags, bullet points?
* [ ] over all it’s a LOT of information. it’s cool that you’ve done so much, but how can you make it easy for a busy hiring manager to scan?
* [ ] also i’d add a print/download button, because it’s not obvious that you would have made a print stylesheet :wink:
* [ ] You don't actually have your college degree on here. It's a basic qualifier for jobs so you need to list it out somewhere obvious
* [ ] With the CFA job, you might want to put "Fellow - Developer" or something like that. You want to specify that you were a software engineer.
* [ ] It is a lot of text. You break it up with the blue, but there's still a lot of stuff to read generally. I recently switched to bullet points. It's something to consider.
* [ ] You want to mention #s. How many clients at thoughtbot? How many user interviews with administrative? How many people within SeaIT? How many volunteers?
* [ ] Your resume doesn't give me a sense as to the magnitude of # of people you've worked with. It doesn't have to be big. Maybe you worked with 4 clients at thoughtbot over 6-month periods each.
* [ ] I know you also rotated who was doing project management at thoughtbot, so you should mention if you ever did anything outside of code - like being the primary point person for the client. This is really atypical generally to have a dev handle this, and you want to breakout of engineering stuff, and it means that you can also work client-facing. These are all atypical things (and also stuff you did at CFA), and that owuld set you apart, so think about that
* [ ] (also I'm looking at this in PDF format. You NEED to put a button to get this in PDF format on your website. PEople will not instinctually know to "print" this out and you want to give the person the option - as they might work in HR and just have a checklist for initial scanning of resumes - without bugging them that they can't get a PDF version.)
* [ ] With the CfSF, you say that OpenReferral worked wth APD. YOU worked with APD as part of open referral.
* [ ] A lot of these have extra language generally about what you did that, even with the prose format, you don't need. I know that your Microsoft internship was 3-months. There's 5 words that I fall asleep on bc you don't need to re-tell me.
* [ ] Also, with ACM - spell it out in the Org title.
* [ ] You don't define MSU bc you don't ave your college degree on here
* [ ] Also mention that you were a founding member in your title, and definitely at the beginning of the first sentence. It's probably one of the most important things of this paragraph. And bold it.
* [ ] Think about "What do I have that others might not", as well as "how can I give the person reading this the most accurate idea of the awesome work i've done" and "how do I show my impact"
* [ ] You STARTED a club. It had XXX members by the time you left. You expanded membership and engagement by XX times. You gave XX talks / seminars / led hackathons.
* [ ] Think about how to talk about this, with EVERYTHING on here
* [ ] Also, you need to surface the fact that you were the sole developer at CFA first.
* [ ] I don't know if the 13k lines of code in 7 months is impressive in coding world. I thought it was.  Maybe add that.
